### ISSUE TITLE
Silkscreen Top

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/OLED01#1]
U I2C konektoru je překlep. Místo SCL je CLK.

**Comment by roman-dvorak** [comment]
Na nabíječce je [Li-ion charger](https://github.com/ODZ-UJF-AV-CR/Li-ion-Charger) je display používán obráceně (o 180 deg) než bylo při návrhu zamýšleno. Je nutné zjistit, jestli je to chyba umístění displaye/popisků. Nebo jestli je to věc konkrétního použití displaye a jak je složité obraz otočit. 

Bylo to zamýšleno tak, aby kablíky vedly "nad" displayem a nepřekážely v pohledu. Zároveň aby bylo možné display umístit na svislo a hřebínek osadit reverzně.

**Comment by roman-dvorak** [comment]
![obrazek](https://github.com/mlab-modules/OLED01/assets/5196729/90ba1a9c-278c-4d5a-a877-2f6a97a0486c)
